In [162]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [163]:
train = pd.read_csv('train.csv', index_col = 0)
train.head()

,lobby_type,r1_hero,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_hero,r2_xp,...,radiant_ward_sentry_count,radiant_first_ward_time,dire_bottle_time,dire_courier_time,dire_flying_courier_time,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time
fight_id,,,,,,,,,,,,,,,,,,,,,
0,0,21,22443,17670,165,13,0,30,6,23496,...,7,54.65332,NaN,NaN,400.16898,36,4,3,1,2.86596
1,0,22,18303,14005,109,9,0,38,16,15909,...,3,-23.60504,NaN,NaN,202.87660,46,5,14,11,-4.13422
2,7,76,22313,17257,247,4,0,51,98,20721,...,32,-24.89392,NaN,NaN,226.01148,46,5,19,16,-14.76307
3,7,4,15055,11879,112,11,0,27,44,16640,...,4,-0.56653,NaN,NaN,1027.51575,38,4,14,12,-21.56140
4,7,43,13003,12716,167,0,0,19,36,15265,...,1,0.29993,NaN,NaN,517.10706,38,5,2,0,475.45059

In [164]:
train = train.drop(['first_blood_time'], axis = 1)
train = train.drop(['first_blood_team'], axis = 1)
train = train.drop(['first_blood_player1'], axis = 1)
train = train.drop(['first_blood_player2'], axis = 1)
train = train.drop(['radiant_courier_time'], axis = 1)
train = train.drop(['dire_courier_time'], axis = 1)

In [165]:
train['dire_bottle_time'] = train['dire_bottle_time'].fillna(train['dire_bottle_time'].mean())

In [166]:
train['radiant_bottle_time'] = train['radiant_bottle_time'].fillna(train['radiant_bottle_time'].mean())

In [167]:
target = pd.read_csv('target.csv', index_col = 0)['radiant_won']

In [168]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49088 entries, 0 to 49087
Data columns (total 85 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   lobby_type                   49088 non-null  int64
 1   r1_hero                      49088 non-null  int64
 2   r1_xp                        49088 non-null  int64
 3   r1_gold                      49088 non-null  int64
 4   r1_lh                        49088 non-null  int64
 5   r1_kills                     49088 non-null  int64
 6   r1_deaths                    49088 non-null  int64
 7   r1_items                     49088 non-null  int64
 8   r2_hero                      49088 non-null  int64
 9   r2_xp                        49088 non-null  int64
 10  r2_gold                      49088 non-null  int64
 11  r2_lh                        49088 non-null  int64
 12  r2_kills                     49088 non-null  int64
 13  r2_deaths                    49088 non-null  int64
 14  r2_items                     49088 non-null  int64
 15  r3_hero                      49088 non-null  int64
 16  r3_xp                        49088 non-null  int64
 17  r3_gold                      49088 non-null  int64
 18  r3_lh                        49088 non-null  int64
 19  r3_kills                     49088 non-null  int64
 20  r3_deaths                    49088 non-null  int64
 21  r3_items                     49088 non-null  int64
 22  r4_hero                      49088 non-null  int64
 23  r4_xp                        49088 non-null  int64
 24  r4_gold                      49088 non-null  int64
 25  r4_lh                        49088 non-null  int64
 26  r4_kills                     49088 non-null  int64
 27  r4_deaths                    49088 non-null  int64
 28  r4_items                     49088 non-null  int64
 29  r5_hero                      49088 non-null  int64
 30  r5_xp                        49088 non-null  int64
 31  r5_gold                      49088 non-null  int64
 32  r5_lh                        49088 non-null  int64
 33  r5_kills                     49088 non-null  int64
 34  r5_deaths                    49088 non-null  int64
 35  r5_items                     49088 non-null  int64
 36  d1_hero                      49088 non-null  int64
 37  d1_xp                        49088 non-null  int64
 38  d1_gold                      49088 non-null  int64
 39  d1_lh                        49088 non-null  int64
 40  d1_kills                     49088 non-null  int64
 41  d1_deaths                    49088 non-null  int64
 42  d1_items                     49088 non-null  int64
 43  d2_hero                      49088 non-null  int64
 44  d2_xp                        49088 non-null  int64
 45  d2_gold                      49088 non-null  int64
 46  d2_lh                        49088 non-null  int64
 47  d2_kills                     49088 non-null  int64
 48  d2_deaths                    49088 non-null  int64
 49  d2_items                     49088 non-null  int64
 50  d3_hero                      49088 non-null  int64
 51  d3_xp                        49088 non-null  int64
 52  d3_gold                      49088 non-null  int64
 53  d3_lh                        49088 non-null  int64
 54  d3_kills                     49088 non-null  int64
 55  d3_deaths                    49088 non-null  int64
 56  d3_items                     49088 non-null  int64
 57  d4_hero                      49088 non-null  int64
 58  d4_xp                        49088 non-null  int64
 59  d4_gold                      49088 non-null  int64
 60  d4_lh                        49088 non-null  int64
 61  d4_kills                     49088 non-null  int64
 62  d4_deaths                    49088 non-null  int64
 63  d4_items                     49088 non-null  int64
 64  d5_hero                      49088 non-null  int64
 65  d5_xp                        49088 non-null  int64
 66  d5_gold                      49088 non-null  int64
 67  d5_lh                        49088 non-null  int64
 68  d5_kills                     49088 non-null  int64
 69  d5_deaths                    49088 non-null  int64
 70  d5_items                     49088 non-null  int64
 71  radiant_bottle_time          49088 non-null  float64
 72  radiant_flying_courier_time  46623 non-null  float64
 73  radiant_tpscroll_count       49088 non-null  int64
 74  radiant_boots_count          49088 non-null  int64
 75  radiant_ward_observer_count  49088 non-null  int64
 76  radiant_ward_sentry_count    49088 non-null  int64
 77  radiant_first_ward_time      47252 non-null  float64
 78  dire_bottle_time             49088 non-null  float64
 79  dire_flying_courier_time     46547 non-null  float64
 80  dire_tpscroll_count          49088 non-null  int64
 81  dire_boots_count             49088 non-null  int64
 82  dire_ward_observer_count     49088 non-null  int64
 83  dire_ward_sentry_count       49088 non-null  int64
 84  dire_first_ward_time         47021 non-null  float64
dtypes: float64(6), int64(79)
memory usage: 32.2 MB

In [169]:
train['radiant_gold'] = train['r1_gold'] + train['r2_gold'] + train['r3_gold'] + train['r4_gold'] + train['r5_gold']
train['dire_gold'] = train['d1_gold'] + train['d2_gold'] + train['d3_gold'] + train['d4_gold'] + train['d5_gold']
train['gold_diff'] = train['radiant_gold'] - train['dire_gold']
train.drop(['radiant_gold', 'dire_gold'], axis=1, inplace=True)

In [170]:
train['radiant_kills'] = train['r1_kills'] + train['r2_kills'] + train['r3_kills'] + train['r4_kills'] + train['r5_kills']
train['dire_kills'] = train['d1_kills'] + train['d2_kills'] + train['d3_kills'] + train['d4_kills'] + train['d5_kills']
train['kills_diff'] = train['radiant_kills'] - train['dire_kills']
train.drop(['radiant_kills', 'dire_kills'], axis=1, inplace=True)

In [171]:
train['radiant_deaths'] = train['r1_deaths'] + train['r2_deaths'] + train['r3_deaths'] + train['r4_deaths'] + train['r5_deaths']
train['dire_deaths'] = train['d1_deaths'] + train['d2_deaths'] + train['d3_deaths'] + train['d4_deaths'] + train['d5_deaths']
train['deaths_diff'] = train['radiant_deaths'] - train['dire_deaths']
train.drop(['radiant_deaths', 'dire_deaths'], axis=1, inplace=True)

In [172]:
train['radiant_items'] = train['r1_items'] + train['r2_items'] + train['r3_items'] + train['r4_items'] + train['r5_items']
train['dire_items'] = train['d1_items'] + train['d2_items'] + train['d3_items'] + train['d4_items'] + train['d5_items']
train['items_diff'] = train['radiant_items'] - train['dire_items']
train.drop(['radiant_items', 'dire_items'], axis=1, inplace=True)

In [173]:
train['radiant_xp'] = train['r1_xp'] + train['r2_xp'] + train['r3_xp'] + train['r4_xp'] + train['r5_xp']
train['dire_xp'] = train['d1_xp'] + train['d2_xp'] + train['d3_xp'] + train['d4_xp'] + train['d5_xp']
train['xp_diff'] = train['radiant_xp'] - train['dire_xp']
train.drop(['radiant_xp', 'dire_xp'], axis=1, inplace=True)

In [174]:
train['radiant_lh'] = train['r1_lh'] + train['r2_lh'] + train['r3_lh'] + train['r4_lh'] + train['r5_lh']
train['dire_lh'] = train['d1_lh'] + train['d2_lh'] + train['d3_lh'] + train['d4_lh'] + train['d5_lh']
train['lh_diff'] = train['radiant_lh'] - train['dire_lh']
train.drop(['radiant_lh', 'dire_lh'], axis=1, inplace=True)

In [175]:
train['radiant_hero'] = train['r1_hero'] + train['r2_hero'] + train['r3_hero'] + train['r4_hero'] + train['r5_hero']
train['dire_hero'] = train['d1_hero'] + train['d2_hero'] + train['d3_hero'] + train['d4_hero'] + train['d5_hero']
train['hero_diff'] = train['radiant_hero'] - train['dire_hero']
train.drop(['radiant_hero', 'dire_hero'], axis=1, inplace=True)

In [186]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=1)

In [187]:
x_train = x_train.fillna(0)
x_val = x_val.fillna(0)

In [188]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.fit_transform(x_val)

In [189]:
import lightgbm as lgb

In [190]:
lgb_train = lgb.Dataset(x_train, y_train)
lgb_eval = lgb.Dataset(x_val, y_val, reference = lgb.train)

In [191]:
params = { 
          'max_depth': 9, 
          'boosting_type': 'gbdt',
          'objective': 'binary',
          'metric': ['auc'],
          'learning_rate': 0.05,
          'seed': 10
}

In [192]:
gbm = lgb.train(params, lgb_train,
            num_boost_round=100,
            valid_sets=[lgb_train, lgb_eval],
            early_stopping_rounds=10)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 19656, number of negative: 19614
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.076370 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13341
[LightGBM] [Info] Number of data points in the train set: 39270, number of used features: 81
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500535 -> initscore=0.002139
[LightGBM] [Info] Start training from score 0.002139
[1]	training's auc: 0.629247	valid_1's auc: 0.614568
Training until validation scores don't improve for 10 rounds
[2]	training's auc: 0.634506	valid_1's auc: 0.618115
[3]	training's auc: 0.637389	valid_1's auc: 0.619152
[4]	training's auc: 0.639116	valid_1's auc: 0.620376
[5]	training's auc: 0.641633	valid_1's auc: 0.620632
[6]	training's auc: 0.642719	valid_1's auc: 0.620509
[7]	training's auc: 0.643393	valid_1's auc: 0.620539
[8]	training's auc: 0.644269	valid_1's auc: 0.621469
[9]	training's auc: 0.645305	valid_1's auc: 0.621542
[10]	training's auc: 0.646375	valid_1's auc: 0.621763
[11]	training's auc: 0.647421	valid_1's auc: 0.621352
[12]	training's auc: 0.648276	valid_1's auc: 0.622155
[13]	training's auc: 0.648922	valid_1's auc: 0.621671
[14]	training's auc: 0.649622	valid_1's auc: 0.622447
[15]	training's auc: 0.650293	valid_1's auc: 0.621873
[16]	training's auc: 0.65095	valid_1's auc: 0.622274
[17]	training's auc: 0.651433	valid_1's auc: 0.623079
[18]	training's auc: 0.652104	valid_1's auc: 0.623904
[19]	training's auc: 0.653169	valid_1's auc: 0.623704
[20]	training's auc: 0.653618	valid_1's auc: 0.623578
[21]	training's auc: 0.654434	valid_1's auc: 0.623377
[22]	training's auc: 0.655155	valid_1's auc: 0.623939
[23]	training's auc: 0.6563	valid_1's auc: 0.623605
[24]	training's auc: 0.657182	valid_1's auc: 0.623583
[25]	training's auc: 0.657832	valid_1's auc: 0.624179
[26]	training's auc: 0.658782	valid_1's auc: 0.624207
[27]	training's auc: 0.659534	valid_1's auc: 0.623565
[28]	training's auc: 0.660286	valid_1's auc: 0.623625
[29]	training's auc: 0.660846	valid_1's auc: 0.623699
[30]	training's auc: 0.661602	valid_1's auc: 0.623706
[31]	training's auc: 0.662521	valid_1's auc: 0.623558
[32]	training's auc: 0.663005	valid_1's auc: 0.623619
[33]	training's auc: 0.663444	valid_1's auc: 0.624059
[34]	training's auc: 0.664118	valid_1's auc: 0.623899
[35]	training's auc: 0.66483	valid_1's auc: 0.623798
[36]	training's auc: 0.665522	valid_1's auc: 0.623907
Early stopping, best iteration is:
[26]	training's auc: 0.658782	valid_1's auc: 0.624207

In [193]:
y_predict_p = gbm.predict(x_val)

In [194]:
from sklearn.metrics import accuracy_score, roc_auc_score

In [195]:
print(roc_auc_score(y_val, y_predict_p))

0.6242069654203994